services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: analytica_backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite:////app/data/database.db
    volumes:
      - sqlite_data:/app/data

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: analytica_frontend
    ports:
      - "8501:8501"
    environment:
      - BACKEND_URL=http://backend:8000
    depends_on:
      - backend

  chromadb:
    image: chromadb/chroma
    ports:
      - "8001:8000"
    volumes:
      - chroma_data:/data

volumes:
  sqlite_data:
  chroma_data: