services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8501:8501"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./database.db:/database.db